#:schema node_modules/wrangler/config-schema.json
workers_dev = true
name = "durable-object-repro-local"
compatibility_date = "2024-11-18"
main = "src/index.ts"

services = [{ binding = "WORKER_A", service = "durable-object-repro-a" }]
