#:schema node_modules/wrangler/config-schema.json
name = "durable-object-repro-a"
main = "src/worker.ts"
compatibility_date = "2024-12-18"

[durable_objects]
bindings = [{ name = "FOO_OBJECT", class_name = "FooDurableObject" }]

[[migrations]]
tag = "v1"
new_classes = ["FooDurableObject"]
