#:schema node_modules/wrangler/config-schema.json
name = "durable-object-repro-b"
main = "src/worker.ts"
compatibility_date = "2024-12-18"

services = [{ binding = "WORKER_A", service = "durable-object-repro-a" }]
